# Generated by Django 2.2.7 on 2020-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200106_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='ahvnumber',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bday',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='children',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='nationality',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='street',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='zip',
            field=models.CharField(max_length=25),
        ),
    ]
