# Generated by Django 2.2.7 on 2020-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
