# Generated by Django 2.2.7 on 2020-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='comment',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default=None, max_length=1, null=True, verbose_name='Do you own a Smartphone?'),
        ),
    ]
