# Generated by Django 2.2.7 on 2020-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_userprofileinfo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='ahvnumber',
            field=models.CharField(max_length=25, verbose_name='AHV-Nummer'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bday',
            field=models.CharField(max_length=25, verbose_name='Geburtstag'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='children',
            field=models.CharField(max_length=25, verbose_name='Angaben zu Ihren Kindern, sofern vorhanden (Name & Geburtsdatum)'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(max_length=25, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='comment',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default=None, max_length=2, null=True, verbose_name='Do you own a Smartphone?'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(max_length=25, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(max_length=25, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='nationality',
            field=models.CharField(max_length=25, verbose_name='Nationalität'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='street',
            field=models.CharField(max_length=25, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='zip',
            field=models.CharField(max_length=25, verbose_name='Postleitzahl'),
        ),
    ]
