# Generated by Django 2.2.7 on 2020-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='children',
            field=models.CharField(max_length=225, verbose_name='Angaben zu Ihren Kindern, sofern vorhanden (Name & Geburtsdatum)'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='comment',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default=None, max_length=100, null=True, verbose_name='Do you own a Smartphone?'),
        ),
    ]
