# Generated by Django 2.2.7 on 2020-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_userprofileinfo_zulage_fam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='tel',
            field=models.CharField(default='+41', max_length=25, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='children',
            field=models.CharField(max_length=225, verbose_name='Angaben zu Ihren Kindern, sofern vorhanden (Name & Geburtsdatum, bis 25 Jahre)'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='zulage_fam',
            field=models.CharField(default='Beantragen Sie Familienzulagen? Falls ja, ab wann?', max_length=140),
        ),
    ]
