# Generated by Django 2.2.7 on 2020-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20200106_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='nationality',
            field=models.CharField(choices=[('Schweiz', 'Schweiz'), ('Deutsch', 'Deutsch'), ('Andere', 'Andere')], default=None, max_length=100, null=True, verbose_name='Nationalität'),
        ),
    ]
