# Generated by Django 2.2.7 on 2020-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20200106_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='bic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bank',
            field=models.CharField(default='', max_length=25, verbose_name='Name der Bank'),
        ),
    ]
