# Generated by Django 2.2.7 on 2020-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20200121_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='notfall_name',
            field=models.CharField(default='Vorname, Nachname (z.B. Eltern, Partner/-in)', max_length=45, verbose_name='Notfallkontakt'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='notfall_tel',
            field=models.CharField(default='', max_length=25, verbose_name='Natel Notfallkontakt'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='notfall_wohnort',
            field=models.CharField(default='', max_length=25, verbose_name='Wohnort des Notfallkontakts'),
        ),
    ]
